# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: TechGirlGeek - Ansible Automation
name: Karyn Cassio
author:
  name: "Karyn Cassio"
  avatar: "/assets/images/sideProfile.JPG"
  bio: "By day I am a Senior Consultant automating things, using the power of Ansible, for Red Hat customers. Posts related to my automation work can be found here."
  location: "Denver, Colorado"
  email: "mailto:karyn@techgirlgeek.com"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: https://github.com/techgirlgeek
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: https://linkedin.com/in/karyncassio
    - label: "Instagram"
      icon: "fab fa-instagram"
      url: https://instagram.com/karyns_fitness_journey
    - label: Certs
      icon: "fa-solid fa-stamp"
      url: https://www.credly.com/users/karyn_cassio/badges

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
logo: "/assets/images/Techgirlgeek_Logo.png"

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.26.2"
minimal_mistakes_skin: "dark" # "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

plugins:
  - jekyll-feed
  - jekyll-include-cache

defaults:
  -
    scope:
      path: ""
    values:
      layout: "single"
      author_profile: true
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "posts"
      author_profiles: true
      categories:
        - techgirlgeek

# Site Footer
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      # url:
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: "https://facebook.com/TechGirlGeek"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/techgirlgeek"
    - label: "GitLab"
      icon: "fab fa-fw fa-gitlab"
      # url:
    - label: "Bitbucket"
      icon: "fab fa-fw fa-bitbucket"
      # url:
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/karyns_fitness_journey"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
